set(headers
  include/databento/batch.hpp
  include/databento/compat.hpp
  include/databento/constants.hpp
  include/databento/datetime.hpp
  include/databento/dbn.hpp
  include/databento/dbn_decoder.hpp
  include/databento/dbn_encoder.hpp
  include/databento/dbn_file_store.hpp
  include/databento/detail/buffer.hpp
  include/databento/detail/dbn_buffer_decoder.hpp
  include/databento/detail/http_client.hpp
  include/databento/detail/json_helpers.hpp
  include/databento/detail/scoped_fd.hpp
  include/databento/detail/scoped_thread.hpp
  include/databento/detail/tcp_client.hpp
  include/databento/detail/zstd_stream.hpp
  include/databento/enums.hpp
  include/databento/exceptions.hpp
  include/databento/file_stream.hpp
  include/databento/fixed_price.hpp
  include/databento/flag_set.hpp
  include/databento/historical.hpp
  include/databento/ireadable.hpp
  include/databento/live.hpp
  include/databento/live_blocking.hpp
  include/databento/live_subscription.hpp
  include/databento/live_threaded.hpp
  include/databento/log.hpp
  include/databento/metadata.hpp
  include/databento/pretty.hpp
  include/databento/publishers.hpp
  include/databento/record.hpp
  include/databento/symbol_map.hpp
  include/databento/symbology.hpp
  include/databento/timeseries.hpp
  include/databento/v1.hpp
  include/databento/v2.hpp
  include/databento/v3.hpp
  include/databento/with_ts_out.hpp
  src/stream_op_helper.hpp
)

set(sources
  src/batch.cpp
  src/datetime.cpp
  src/dbn.cpp
  src/dbn_constants.hpp
  src/dbn_decoder.cpp
  src/dbn_encoder.cpp
  src/dbn_file_store.cpp
  src/detail/buffer.cpp
  src/detail/dbn_buffer_decoder.cpp
  src/detail/http_client.cpp
  src/detail/json_helpers.cpp
  src/detail/scoped_fd.cpp
  src/detail/tcp_client.cpp
  src/detail/zstd_stream.cpp
  src/enums.cpp
  src/exceptions.cpp
  src/file_stream.cpp
  src/flag_set.cpp
  src/historical.cpp
  src/live.cpp
  src/live_blocking.cpp
  src/live_threaded.cpp
  src/log.cpp
  src/metadata.cpp
  src/pretty.cpp
  src/publishers.cpp
  src/record.cpp
  src/symbol_map.cpp
  src/symbology.cpp
  src/v1.cpp
  src/v2.cpp
)
