set(headers
  include/databento/batch.hpp
  include/databento/constants.hpp
  include/databento/datetime.hpp
  include/databento/dbz.hpp
  include/databento/dbz_parser.hpp
  include/databento/file_bento.hpp
  include/databento/enums.hpp
  include/databento/exceptions.hpp
  include/databento/historical.hpp
  include/databento/metadata.hpp
  include/databento/record.hpp
  include/databento/symbology.hpp
  include/databento/timeseries.hpp
  include/databento/detail/file_stream.hpp
  include/databento/detail/http_client.hpp
  include/databento/detail/shared_channel.hpp
  src/scoped_thread.hpp
  src/stream_op_helper.hpp
)

set(sources
  src/batch.cpp
  src/datetime.cpp
  src/dbz.cpp
  src/dbz_parser.cpp
  src/enums.cpp
  src/exceptions.cpp
  src/file_bento.cpp
  src/historical.cpp
  src/metadata.cpp
  src/record.cpp
  src/symbology.cpp
  src/detail/file_stream.cpp
  src/detail/http_client.cpp
  src/detail/shared_channel.cpp
)
